# Generated by Django 2.1.15 on 2020-05-22 05:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basefunction', '0002_daynumber_userip_visitnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='userip',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
