# Generated by Django 2.1.15 on 2020-05-29 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basefunction', '0004_auto_20200523_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('url_link', models.CharField(max_length=100)),
                ('detail', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
