# Generated by Django 2.1.15 on 2020-05-29 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basefunction', '0005_featurepost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featurepost',
            old_name='url_link',
            new_name='url_path',
        ),
    ]
