# Generated by Django 2.1.15 on 2020-05-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basefunction', '0006_auto_20200529_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurepost',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='featurepost',
            name='url_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
