# Generated by Django 3.0.8 on 2020-09-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basefunction', '0008_featurepost_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurepost',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, '正常'), (0, '删除'), (2, '草稿')], default=1),
        ),
    ]
