# Generated by Django 2.1.15 on 2020-05-23 11:07

from django.db import migrations, models
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('session_uid', shortuuidfield.fields.ShortUUIDField(auto_created=True, blank=True, editable=False, max_length=22)),
                ('code', models.CharField(max_length=20)),
                ('uid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('session_name', models.CharField(max_length=30)),
                ('visit_num', models.PositiveIntegerField(default=0)),
                ('status', models.PositiveIntegerField(choices=[(1, '正常'), (0, '删除'), (2, '草稿')], default=2)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
