# Generated by Django 2.1.15 on 2020-05-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='visit_num',
            field=models.PositiveIntegerField(auto_created=True, default=0),
        ),
    ]
