# Generated by Django 2.1.15 on 2020-05-29 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0004_remove_code_show_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
