# Generated by Django 2.1.15 on 2020-05-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peekpauser', '0002_auto_20200523_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
